; ScreenVault Inno Setup Installer Script
; Windows Installer Specification per ScreenVault_Installer_Prompt.md
;
; Look & feel: Windows 11 style wizard that follows the user's light/dark mode, branded artwork
; (installer/assets, generated by tools/branding/generate_assets.py) and modern task dialogs.
; Requires Inno Setup 6.7 or newer; Inno Setup 7 additionally builds a native 64-bit Setup.

#if Ver < EncodeVer(6,7,0)
  #error ScreenVault's installer needs Inno Setup 6.7 or newer (modern light/dark wizard). Download the latest version from https://jrsoftware.org/isdl.php
#endif

#ifndef AppVersion
  #define AppVersion "1.2.0"
#endif

#define AppName "ScreenVault"
#define AppExe "ScreenVault.exe"
#define AppMutexName "ScreenVault-7C0A45B9-F2D7-4952-B79D-5B6608C42589"

#define WizardImages "assets\wizard-100.png,assets\wizard-125.png,assets\wizard-150.png,assets\wizard-175.png,assets\wizard-200.png,assets\wizard-250.png"
#define WizardImagesDark "assets\wizard-dark-100.png,assets\wizard-dark-125.png,assets\wizard-dark-150.png,assets\wizard-dark-175.png,assets\wizard-dark-200.png,assets\wizard-dark-250.png"
#define WizardSmallImages "assets\wizard-small-55.png,assets\wizard-small-64.png,assets\wizard-small-83.png,assets\wizard-small-92.png,assets\wizard-small-110.png,assets\wizard-small-138.png"

[Setup]
AppId={{7C0A45B9-F2D7-4952-B79D-5B6608C42589}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher=ScreenVault
AppComments=Always-on, crash-proof screen and meeting recorder
VersionInfoVersion={#AppVersion}
VersionInfoDescription={#AppName} Setup
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DisableWelcomePage=no
DisableDirPage=auto
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog commandline
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
#if Ver >= EncodeVer(7,0,0)
SetupArchitecture=x64
#endif
MinVersion=10.0.17763
; Look & feel: modern wizard, branded artwork.
WizardStyle=modern
WizardSizePercent=120
WizardBackColor=#F7F7FB
WizardImageFile={#WizardImages}
WizardSmallImageFile={#WizardSmallImages}
SetupIconFile=assets\ScreenVault.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
LicenseFile=assets\LICENSE.txt
OutputDir=..\dist
OutputBaseFilename=ScreenVault_Setup_{#AppVersion}
Compression=lzma2/ultra64
SolidCompression=yes
SetupMutex=ScreenVaultSetupMutex
CloseApplications=yes
RestartApplications=no
UsePreviousAppDir=yes
UsePreviousTasks=yes

[Messages]
WelcomeLabel1=Welcome to [name]
WelcomeLabel2=Setup will install [name/ver] on this computer.%n%n[name] records your screen, microphone and meeting audio — and keeps recording when devices change, apps crash or a drive fills up.%n%nA red dot in the notification area always shows when recording is on.
SelectTasksLabel2=Choose how [name] starts. You can change all of this later in Settings.
FinishedHeadingLabel=[name] is ready
FinishedLabel=[name] runs in the notification area next to the clock. Click its icon at any time to start recording, check your audio or open your recordings.
ClickFinish=Click Finish to close Setup.

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Shortcuts:"
Name: "startwithwindows"; Description: "Start ScreenVault when I sign in (runs quietly in the notification area, does not record)"; GroupDescription: "When Windows starts:"
Name: "startrecording"; Description: "Start recording automatically when ScreenVault starts"; GroupDescription: "When Windows starts:"; Flags: unchecked

[Files]
Source: "..\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExe}"; Comment: "Always-on screen and meeting recorder"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Comment: "Always-on screen and meeting recorder"; Tasks: desktopicon

[Registry]
; All-users autostart only. Per-user installs: the app manages its own HKCU Run value.
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "{#AppName}"; \
  ValueData: """{app}\{#AppExe}"" --autostart --minimize-to-tray"; Flags: uninsdeletevalue; \
  Tasks: startwithwindows; Check: IsAdminInstallMode

[Run]
; Upgrade while the app was running: relaunch silently (also in silent installs), resume recording if it was recording.
Filename: "{app}\{#AppExe}"; Parameters: "--minimize-to-tray --after-upgrade"; Flags: nowait runasoriginaluser; Check: WasRunningBefore
; Normal install: optional launch from the Finish page.
Filename: "{app}\{#AppExe}"; Description: "Launch {#AppName} now"; Flags: nowait postinstall skipifsilent runasoriginaluser; Check: not WasRunningBefore

[UninstallDelete]
Type: files; Name: "{app}\install-defaults.json"

[Code]
const
  DRIVE_FIXED = 3;
  ONE_GB = 1073741824;

function GetDriveType(lpRootPathName: String): Cardinal;
  external 'GetDriveTypeW@kernel32.dll stdcall';

var
  StoragePage: TInputDirWizardPage;
  lblPrimaryFree: TNewStaticText;
  lblBackupFree: TNewStaticText;
  barPrimary: TNewProgressBar;
  barBackup: TNewProgressBar;
  lblStorageHint: TNewStaticText;
  WasRunning: Boolean;
  StoragePageShown: Boolean;
  DefaultPrimaryValue: String;
  UninstPrimaryDir: String;
  UninstBackupDir: String;

{ Helper: JSON escape backslashes and double quotes }
function JsonEscape(const S: String): String;
var
  I: Integer;
  R: String;
begin
  R := '';
  for I := 1 to Length(S) do
  begin
    if S[I] = '\' then
      R := R + '\\'
    else if S[I] = '"' then
      R := R + '\"'
    else
      R := R + S[I];
  end;
  Result := R;
end;

{ Helper: Get root path with trailing backslash }
function GetPathDriveRoot(const Path: String): String;
var
  Drive: String;
begin
  if (Length(Path) >= 2) and (Path[1] = '\') and (Path[2] = '\') then
  begin
    Result := ''; { UNC path has no drive letter root }
    Exit;
  end;
  Drive := ExtractFileDrive(Path);
  if Drive <> '' then
    Result := AddBackslash(Drive)
  else
    Result := '';
end;

function IsNetworkPath(const Path: String): Boolean;
begin
  Result := (Length(Path) >= 2) and (Path[1] = '\') and (Path[2] = '\');
end;

{ Shows free space for a folder as text plus a disk-usage bar (amber below 10 GB, red below 5 GB). }
procedure DescribeDisk(const Path: String; const Lbl: TNewStaticText; const Bar: TNewProgressBar);
var
  DriveRoot: String;
  FreeBytes, TotalBytes: Int64;
  FreeGb, TotalGb, UsedPct: Int64;
begin
  Bar.Position := 0;
  Bar.State := npbsNormal;

  if Trim(Path) = '' then
  begin
    Lbl.Caption := 'Not set';
    Exit;
  end;

  if IsNetworkPath(Path) then
  begin
    Lbl.Caption := 'Network folder — it may disconnect during a recording';
    Bar.State := npbsPaused;
    Bar.Position := 100;
    Exit;
  end;

  DriveRoot := GetPathDriveRoot(Path);
  if (DriveRoot <> '') and GetSpaceOnDisk64(DriveRoot, FreeBytes, TotalBytes) and (TotalBytes > 0) then
  begin
    FreeGb := FreeBytes div ONE_GB;
    TotalGb := TotalBytes div ONE_GB;
    UsedPct := ((TotalBytes - FreeBytes) div ONE_GB) * 100 div (TotalGb + 1);
    Bar.Position := UsedPct;
    if FreeGb < 5 then
      Bar.State := npbsError
    else if FreeGb < 10 then
      Bar.State := npbsPaused;
    Lbl.Caption := IntToStr(FreeGb) + ' GB free of ' + IntToStr(TotalGb) + ' GB on ' + RemoveBackslash(DriveRoot);
  end
  else if DriveRoot <> '' then
    Lbl.Caption := 'Drive ' + RemoveBackslash(DriveRoot) + ' is not available'
  else
    Lbl.Caption := 'Enter a full path, for example D:\Recordings';
end;

{ Event handler for edit box changes to update free space labels and bars }
procedure OnStorageEditChange(Sender: TObject);
var
  PrimaryRoot, BackupRoot: String;
begin
  if not Assigned(StoragePage) then
    Exit;

  DescribeDisk(StoragePage.Values[0], lblPrimaryFree, barPrimary);
  DescribeDisk(StoragePage.Values[1], lblBackupFree, barBackup);

  PrimaryRoot := GetPathDriveRoot(Trim(StoragePage.Values[0]));
  BackupRoot := GetPathDriveRoot(Trim(StoragePage.Values[1]));
  if Trim(StoragePage.Values[1]) = '' then
    lblStorageHint.Caption := 'Tip: add a backup folder on another drive so recording can continue if the primary drive fills up.'
  else if (PrimaryRoot <> '') and SameText(PrimaryRoot, BackupRoot) then
    lblStorageHint.Caption := 'Both folders are on the same drive, so the backup will not help when that drive is full.'
  else
    lblStorageHint.Caption := 'If the primary drive gets low on space, recording continues on the backup drive without a gap.';
end;

{ Detect the largest secondary fixed drive }
function DetectDefaultBackupLocation(const PrimaryDriveRoot: String): String;
var
  DriveCode: Integer;
  Root: String;
  FreeBytes, TotalBytes: Int64;
  LargestBytes: Int64;
  BestDrive: String;
begin
  LargestBytes := 0;
  BestDrive := '';

  for DriveCode := Ord('C') to Ord('Z') do
  begin
    Root := Chr(DriveCode) + ':\';
    if GetDriveType(Root) = DRIVE_FIXED then
    begin
      if not SameText(Root, PrimaryDriveRoot) then
      begin
        if GetSpaceOnDisk64(Root, FreeBytes, TotalBytes) then
        begin
          if TotalBytes > LargestBytes then
          begin
            LargestBytes := TotalBytes;
            BestDrive := Root;
          end;
        end;
      end;
    end;
  end;

  if BestDrive <> '' then
    Result := AddBackslash(BestDrive) + 'ScreenVault Backup'
  else
    Result := '';
end;

{ Determine if an upgrade is happening }
function IsUpgrade(): Boolean;
var
  OldExe: String;
begin
  OldExe := AddBackslash(WizardDirValue) + '{#AppExe}';
  Result := (WizardForm.PrevAppDir <> '') or FileExists(OldExe);
end;

function WasRunningBefore(): Boolean;
begin
  Result := WasRunning;
end;

{ Places a disk-usage bar and caption under an edit box; returns the height used. }
function AddDiskInfo(const Edit: TEdit; var Bar: TNewProgressBar; var Lbl: TNewStaticText): Integer;
begin
  Bar := TNewProgressBar.Create(StoragePage);
  Bar.Parent := StoragePage.Surface;
  Bar.Left := Edit.Left;
  Bar.Top := Edit.Top + Edit.Height + ScaleY(6);
  Bar.Width := Edit.Width;
  Bar.Height := ScaleY(6);
  Bar.Min := 0;
  Bar.Max := 100;

  Lbl := TNewStaticText.Create(StoragePage);
  Lbl.Parent := StoragePage.Surface;
  Lbl.Left := Edit.Left;
  Lbl.Top := Bar.Top + Bar.Height + ScaleY(4);
  Lbl.Width := Edit.Width;
  Lbl.AutoSize := False;
  Lbl.Height := ScaleY(16);
  Lbl.Font.Color := clGrayText;

  Result := (Lbl.Top + Lbl.Height) - (Edit.Top + Edit.Height) + ScaleY(8);
end;

procedure InitializeWizard();
var
  ParamPrimary, ParamBackup: String;
  PrimaryRoot: String;
  DefaultBackupValue: String;
  ExtraTop: Integer;
begin
  StoragePageShown := False;
  WasRunning := False;

  { 1. Recording storage page }
  StoragePage := CreateInputDirPage(
    wpSelectDir,
    'Recording storage',
    'Where should ScreenVault save your recordings?',
    'Recordings are saved to the primary folder. If that drive gets low on space, ScreenVault automatically continues in the backup folder, so a meeting is never lost. You can change this later in Settings > Storage.',
    False,
    'New Folder');

  StoragePage.Add('Primary folder:');
  StoragePage.Add('Backup folder (on a different drive, optional):');

  { Default values }
  DefaultPrimaryValue := ExpandConstant('{%USERPROFILE}') + '\Videos\Screen Recordings';
  PrimaryRoot := GetPathDriveRoot(DefaultPrimaryValue);
  DefaultBackupValue := DetectDefaultBackupLocation(PrimaryRoot);

  { Command-line parameter overrides for silent installs }
  ParamPrimary := ExpandConstant('{param:PRIMARY|}');
  ParamBackup := ExpandConstant('{param:BACKUP|}');

  if ParamPrimary <> '' then
    StoragePage.Values[0] := ParamPrimary
  else
    StoragePage.Values[0] := DefaultPrimaryValue;

  if ParamBackup <> '' then
    StoragePage.Values[1] := ParamBackup
  else
    StoragePage.Values[1] := DefaultBackupValue;

  { Disk usage bar + free-space caption under each folder; shift the second group down to make room }
  ExtraTop := AddDiskInfo(StoragePage.Edits[0], barPrimary, lblPrimaryFree);
  StoragePage.PromptLabels[1].Top := StoragePage.PromptLabels[1].Top + ExtraTop;
  StoragePage.Edits[1].Top := StoragePage.Edits[1].Top + ExtraTop;
  StoragePage.Buttons[1].Top := StoragePage.Buttons[1].Top + ExtraTop;
  AddDiskInfo(StoragePage.Edits[1], barBackup, lblBackupFree);

  lblStorageHint := TNewStaticText.Create(StoragePage);
  lblStorageHint.Parent := StoragePage.Surface;
  lblStorageHint.Left := StoragePage.Edits[1].Left;
  lblStorageHint.Top := lblBackupFree.Top + lblBackupFree.Height + ScaleY(12);
  lblStorageHint.Width := StoragePage.SurfaceWidth - lblStorageHint.Left;
  lblStorageHint.AutoSize := False;
  lblStorageHint.WordWrap := True;
  lblStorageHint.Height := ScaleY(34);

  StoragePage.Edits[0].OnChange := @OnStorageEditChange;
  StoragePage.Edits[1].OnChange := @OnStorageEditChange;
  OnStorageEditChange(nil);
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if Assigned(StoragePage) and (PageID = StoragePage.ID) then
  begin
    { Skip storage page on upgrade unless /RECONFIGURE was passed }
    if IsUpgrade() and (ExpandConstant('{param:RECONFIGURE|}') = '') then
    begin
      Result := True;
      StoragePageShown := False;
    end
    else
    begin
      Result := False;
      StoragePageShown := True;
    end;
  end;
end;

{ Yes/No task dialog with explicit button labels; returns True when the first button is chosen. }
function AskToContinue(const Instruction, Text, ContinueLabel, BackLabel: String): Boolean;
begin
  Result := TaskDialogMsgBox(Instruction, Text, mbConfirmation, MB_YESNO, [ContinueLabel, BackLabel], 0) = IDYES;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  PrimaryPath, BackupPath: String;
  PrimaryRoot, BackupRoot: String;
  FreeBytes, TotalBytes: Int64;
  FreeGb: Int64;
begin
  Result := True;
  if Assigned(StoragePage) and (CurPageID = StoragePage.ID) then
  begin
    StoragePageShown := True;
    PrimaryPath := Trim(StoragePage.Values[0]);
    BackupPath := Trim(StoragePage.Values[1]);

    { 1. Primary empty -> Error }
    if PrimaryPath = '' then
    begin
      TaskDialogMsgBox('Choose a primary folder', 'ScreenVault needs a folder to save recordings in.', mbError, MB_OK, [], 0);
      Result := False;
      Exit;
    end;

    { 2. Primary drive doesn't exist -> Error }
    PrimaryRoot := GetPathDriveRoot(PrimaryPath);
    if (PrimaryRoot <> '') and not DirExists(PrimaryRoot) then
    begin
      TaskDialogMsgBox('That drive does not exist', 'The drive for the primary recording folder (' + PrimaryRoot + ') was not found. Choose a folder on another drive.', mbError, MB_OK, [], 0);
      Result := False;
      Exit;
    end;

    { 3. Primary and backup on the same drive -> Warning }
    BackupRoot := GetPathDriveRoot(BackupPath);
    if (BackupPath <> '') and (PrimaryRoot <> '') and (BackupRoot <> '') and SameText(PrimaryRoot, BackupRoot) then
    begin
      if not AskToContinue('Use the same drive for both folders?',
        'The backup folder is on the same drive as the primary folder, so it will not help if that drive becomes full.',
        'Continue anyway', 'Choose another folder') then
      begin
        Result := False;
        Exit;
      end;
    end;

    { 4. Backup empty -> Warning }
    if BackupPath = '' then
    begin
      if not AskToContinue('Continue without a backup folder?',
        'Without a backup folder, recording stops if the primary drive fills up.',
        'Continue without backup', 'Add a backup folder') then
      begin
        Result := False;
        Exit;
      end;
    end;

    { 5. UNC / network path warning }
    if IsNetworkPath(PrimaryPath) or IsNetworkPath(BackupPath) then
    begin
      if not AskToContinue('Use a network folder?',
        'Network folders can disconnect unexpectedly during a recording. A local drive is more reliable.',
        'Use the network folder', 'Choose a local folder') then
      begin
        Result := False;
        Exit;
      end;
    end;

    { 6. Primary drive free space < 10 GB warning }
    if (PrimaryRoot <> '') and GetSpaceOnDisk64(PrimaryRoot, FreeBytes, TotalBytes) then
    begin
      FreeGb := FreeBytes div ONE_GB;
      if FreeGb < 10 then
      begin
        if not AskToContinue('The primary drive is almost full',
          'Drive ' + PrimaryRoot + ' has only ' + IntToStr(FreeGb) + ' GB free. An hour of recording can use up to 1.5 GB.',
          'Continue anyway', 'Choose another folder') then
        begin
          Result := False;
          Exit;
        end;
      end;
    end;
  end;
end;

function UpdateReadyMemo(Space, NewLine, MemoUserInfoInfo, MemoDirInfo, MemoTypeInfo,
  MemoComponentsInfo, MemoGroupInfo, MemoTasksInfo: String): String;
var
  S: String;
begin
  S := '';
  if MemoDirInfo <> '' then
    S := S + MemoDirInfo + NewLine + NewLine;

  if Assigned(StoragePage) then
  begin
    S := S + 'Recording storage:' + NewLine;
    S := S + Space + 'Primary: ' + StoragePage.Values[0] + NewLine;
    if Trim(StoragePage.Values[1]) <> '' then
      S := S + Space + 'Backup:  ' + StoragePage.Values[1] + NewLine
    else
      S := S + Space + 'Backup:  (none)' + NewLine;
    S := S + NewLine;
  end;

  if MemoTasksInfo <> '' then
    S := S + MemoTasksInfo + NewLine;

  Result := S;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode, I: Integer;
  OldExe: String;
begin
  Result := '';
  OldExe := AddBackslash(WizardDirValue) + '{#AppExe}';
  WasRunning := CheckForMutexes('{#AppMutexName},Local\{#AppMutexName}');

  if WasRunning and FileExists(OldExe) then
  begin
    { Run as the ORIGINAL user: the app control pipe only accepts the logged-in user }
    ExecAsOriginalUser(OldExe, '--exit --wait', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

    for I := 1 to 30 do
    begin
      if not CheckForMutexes('{#AppMutexName},Local\{#AppMutexName}') then Break;
      Sleep(1000);
    end;

    if CheckForMutexes('{#AppMutexName},Local\{#AppMutexName}') then
      Result := 'ScreenVault is still running. Please exit it from the tray icon (right-click > Exit ScreenVault), then click Next.';
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  DefaultsFile: String;
  PrimaryVal, BackupVal: String;
  PrimaryJson, BackupJson: String;
  ScopeJson, VersionJson, RevJson: String;
  StartWinJson, StartRecJson: String;
  JsonContent: String;
begin
  if CurStep = ssPostInstall then
  begin
    { Write install-defaults.json on fresh install or when storage page was shown }
    if (not IsUpgrade()) or StoragePageShown then
    begin
      DefaultsFile := AddBackslash(ExpandConstant('{app}')) + 'install-defaults.json';

      if IsAdminInstallMode then
        ScopeJson := '"AllUsers"'
      else
        ScopeJson := '"PerUser"';

      VersionJson := '"' + '{#AppVersion}' + '"';
      RevJson := '"' + GetDateTimeString('yyyy-mm-dd"T"hh:nn:ss', '-', ':') + '"';

      PrimaryVal := Trim(StoragePage.Values[0]);
      { If primary was left as default, pass null so the app uses real user special folder }
      if SameText(PrimaryVal, DefaultPrimaryValue) or (PrimaryVal = '') then
        PrimaryJson := 'null'
      else
        PrimaryJson := '"' + JsonEscape(PrimaryVal) + '"';

      BackupVal := Trim(StoragePage.Values[1]);
      if BackupVal = '' then
        BackupJson := 'null'
      else
        BackupJson := '"' + JsonEscape(BackupVal) + '"';

      if WizardIsTaskSelected('startwithwindows') then
        StartWinJson := 'true'
      else
        StartWinJson := 'false';

      if WizardIsTaskSelected('startrecording') then
        StartRecJson := 'true'
      else
        StartRecJson := 'false';

      JsonContent := '{' + #13#10 +
        '  "installScope": ' + ScopeJson + ',' + #13#10 +
        '  "installerVersion": ' + VersionJson + ',' + #13#10 +
        '  "defaultsRevision": ' + RevJson + ',' + #13#10 +
        '  "primaryLocation": ' + PrimaryJson + ',' + #13#10 +
        '  "backupLocation": ' + BackupJson + ',' + #13#10 +
        '  "startWithWindows": ' + StartWinJson + ',' + #13#10 +
        '  "startRecordingOnLaunch": ' + StartRecJson + #13#10 +
        '}';

      SaveStringToFile(DefaultsFile, JsonContent, False);
    end;
  end;
end;

{ Helper: Extract storage location from install-defaults.json }
function ExtractJsonStringValue(const Json, Key: String): String;
var
  P, ColonPos, QuoteStart, QuoteEnd: Integer;
begin
  Result := '';
  P := Pos('"' + Key + '"', Json);
  if P > 0 then
  begin
    ColonPos := Pos(':', Copy(Json, P, Length(Json) - P + 1));
    if ColonPos > 0 then
    begin
      P := P + ColonPos;
      QuoteStart := Pos('"', Copy(Json, P, Length(Json) - P + 1));
      if QuoteStart > 0 then
      begin
        P := P + QuoteStart;
        QuoteEnd := Pos('"', Copy(Json, P, Length(Json) - P + 1));
        if QuoteEnd > 0 then
          Result := Copy(Json, P, QuoteEnd - 1);
      end;
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode, I: Integer;
  AppExePath, DefaultsFile: String;
  JsonContent: String;
  JsonAnsi: AnsiString;
  NoticeMsg: String;
begin
  if CurUninstallStep = usUninstall then
  begin
    AppExePath := AddBackslash(ExpandConstant('{app}')) + '{#AppExe}';
    DefaultsFile := AddBackslash(ExpandConstant('{app}')) + 'install-defaults.json';

    { Read storage folders from install-defaults.json before deleting files }
    UninstPrimaryDir := '';
    UninstBackupDir := '';
    if FileExists(DefaultsFile) then
    begin
      if LoadStringFromFile(DefaultsFile, JsonAnsi) then
      begin
        JsonContent := String(JsonAnsi);
        UninstPrimaryDir := ExtractJsonStringValue(JsonContent, 'primaryLocation');
        UninstBackupDir := ExtractJsonStringValue(JsonContent, 'backupLocation');
      end;
    end;
    if UninstPrimaryDir = '' then
      UninstPrimaryDir := ExpandConstant('{%USERPROFILE}') + '\Videos\Screen Recordings';

    { 1. Graceful stop: ScreenVault.exe --exit --wait }
    if FileExists(AppExePath) and CheckForMutexes('{#AppMutexName},Local\{#AppMutexName}') then
    begin
      Exec(AppExePath, '--exit --wait', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      for I := 1 to 15 do
      begin
        if not CheckForMutexes('{#AppMutexName},Local\{#AppMutexName}') then Break;
        Sleep(1000);
      end;

      { 2. Force stop fallback }
      if CheckForMutexes('{#AppMutexName},Local\{#AppMutexName}') then
      begin
        Exec('taskkill.exe', '/F /T /IM {#AppExe}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
        Sleep(1000);
      end;
    end;
  end
  else if CurUninstallStep = usPostUninstall then
  begin
    { Remove HKCU Run key for per-user installations }
    RegDeleteValue(HKEY_CURRENT_USER, 'Software\Microsoft\Windows\CurrentVersion\Run', '{#AppName}');

    { Offer to delete settings and logs (never recordings) }
    if MsgBox('Also delete your ScreenVault settings and logs? (Your recordings are NOT affected)', mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
    begin
      DelTree(ExpandConstant('{userappdata}\ScreenVault'), True, True, True);
      DelTree(ExpandConstant('{localappdata}\ScreenVault'), True, True, True);
    end;

    { Always notify that recordings were NOT deleted and where they are }
    NoticeMsg := 'They are still in:' + #13#10 + '  ' + UninstPrimaryDir;
    if UninstBackupDir <> '' then
      NoticeMsg := NoticeMsg + #13#10 + '  ' + UninstBackupDir;

    TaskDialogMsgBox('Your recordings were kept', NoticeMsg, mbInformation, MB_OK, [], 0);
  end;
end;
